services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_URL=http://seq:5341
      - SEQ_FIRSTRUN_ADMINPASSWORD=my-secret-password
    ports:
      - "5341:5341"
    volumes:
      - seq-data:/data

volumes:
  seq-data: